#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
ANDALUS_HOME="${ANDALUS_HOME:-$HOME/.andalus}"
BUNDLED_ANDALUS_HOME="${BUNDLE_ROOT}/.andalus"

if [ -d "$BUNDLED_ANDALUS_HOME" ] && [ "$BUNDLED_ANDALUS_HOME" != "$ANDALUS_HOME" ]; then
  mkdir -p "$ANDALUS_HOME"
  tar -C "$BUNDLED_ANDALUS_HOME" -cf - . | tar -C "$ANDALUS_HOME" -xf -
fi

ANDALUS_CONFIG_DIR="${ANDALUS_CONFIG_DIR:-$ANDALUS_HOME/config}"
ANDALUS_LOG_DIR="${ANDALUS_LOG_DIR:-$ANDALUS_HOME/logs}"
ANDALUS_SERVER_LOG_DIR="${ANDALUS_SERVER_LOG_DIR:-$ANDALUS_LOG_DIR/server}"
ANDALUS_LOG_FILE_PATH="${ANDALUS_LOG_FILE_PATH:-$ANDALUS_SERVER_LOG_DIR/server.log}"
ANDALUS_PLUGINS_DIR="${ANDALUS_PLUGINS_DIR:-$ANDALUS_HOME/plugins}"
ANDALUS_SECRETS_DIR="${ANDALUS_SECRETS_DIR:-$ANDALUS_HOME/secrets}"
ANDALUS_MODELS_DIR="${ANDALUS_MODELS_DIR:-$ANDALUS_HOME/models}"
ANDALUS_MCP_DIR="${ANDALUS_MCP_DIR:-$ANDALUS_HOME/mcp}"
ANDALUS_RUN_DIR="${ANDALUS_RUN_DIR:-$ANDALUS_HOME/run}"
ANDALUS_VECTOR_DIR="${ANDALUS_VECTOR_DIR:-$ANDALUS_HOME/vector}"
ANDALUS_GOLLEK_HOME="${ANDALUS_GOLLEK_HOME:-$ANDALUS_HOME/gollek}"
LEGACY_GOLLEK_HOME="${GOLLEK_HOME:-$HOME/.gollek}"

if mkdir -p "$ANDALUS_GOLLEK_HOME" 2>/dev/null; then
  GOLLEK_HOME="$ANDALUS_GOLLEK_HOME"
else
  mkdir -p "$LEGACY_GOLLEK_HOME"
  GOLLEK_HOME="$LEGACY_GOLLEK_HOME"
fi

ANDALUS_GOLLEK_MODELS_DIR="${ANDALUS_GOLLEK_MODELS_DIR:-$GOLLEK_HOME/models}"
ANDALUS_GOLLEK_STORAGE_DIR="${ANDALUS_GOLLEK_STORAGE_DIR:-$GOLLEK_HOME/storage}"

mkdir -p \
  "$ANDALUS_CONFIG_DIR" \
  "$ANDALUS_SERVER_LOG_DIR" \
  "$ANDALUS_PLUGINS_DIR" \
  "$ANDALUS_SECRETS_DIR" \
  "$ANDALUS_MODELS_DIR" \
  "$ANDALUS_MCP_DIR" \
  "$ANDALUS_RUN_DIR" \
  "$ANDALUS_VECTOR_DIR" \
  "$ANDALUS_GOLLEK_MODELS_DIR" \
  "$ANDALUS_GOLLEK_STORAGE_DIR"

ANDALUS_EXECUTABLE="${ANDALUS_EXECUTABLE:-$ANDALUS_HOME/bin/andalus}"
if [ ! -x "$ANDALUS_EXECUTABLE" ]; then
  chmod +x "$ANDALUS_EXECUTABLE" 2>/dev/null || true
fi
if [ ! -x "$ANDALUS_EXECUTABLE" ]; then
  echo "Andalus executable not found or not executable: $ANDALUS_EXECUTABLE" >&2
  exit 1
fi

SYSTEMD_USER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_FILE="$SYSTEMD_USER_DIR/andalus.service"
mkdir -p "$SYSTEMD_USER_DIR"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Andalus service
After=network-online.target

[Service]
Type=simple
ExecStart=$ANDALUS_EXECUTABLE
Restart=on-failure
RestartSec=5
Environment=ANDALUS_HOME=$ANDALUS_HOME
Environment=ANDALUS_CONFIG_DIR=$ANDALUS_CONFIG_DIR
Environment=ANDALUS_LOG_DIR=$ANDALUS_LOG_DIR
Environment=ANDALUS_SERVER_LOG_DIR=$ANDALUS_SERVER_LOG_DIR
Environment=ANDALUS_LOG_FILE_PATH=$ANDALUS_LOG_FILE_PATH
Environment=ANDALUS_PLUGINS_DIR=$ANDALUS_PLUGINS_DIR
Environment=ANDALUS_SECRETS_DIR=$ANDALUS_SECRETS_DIR
Environment=ANDALUS_MODELS_DIR=$ANDALUS_MODELS_DIR
Environment=ANDALUS_MCP_DIR=$ANDALUS_MCP_DIR
Environment=ANDALUS_RUN_DIR=$ANDALUS_RUN_DIR
Environment=ANDALUS_VECTOR_DIR=$ANDALUS_VECTOR_DIR
Environment=ANDALUS_GOLLEK_HOME=$ANDALUS_GOLLEK_HOME
Environment=GOLLEK_HOME=$GOLLEK_HOME
Environment=ANDALUS_GOLLEK_MODELS_DIR=$ANDALUS_GOLLEK_MODELS_DIR
Environment=ANDALUS_GOLLEK_STORAGE_DIR=$ANDALUS_GOLLEK_STORAGE_DIR
WorkingDirectory=$ANDALUS_HOME

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now andalus.service
echo "Installed Andalus systemd user service at $SERVICE_FILE"
